# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b281e8f10be1c5b22c376a2ba64e2ec227d5be867fa513bb81aefd28f5e28fadc11ad639b34b3327138e1b3764ad3a2d689efd908d90178aaf60d37e67d4ea7

test:
  secret_key_base: 2a33e19bcd7d26857bad3ca3d75fdfd95db68b7cea3602d5d5240d6abfe9df934114633837cb5d08c0f3438dc24541e7f875e8404aa8517489aebcc1f5019c2e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
